version: "3.10"
services:
  web:
    build: .
    command: bash -c "python -m scripts.split_train_val_test &&
         python -m scripts.train --config_path=configs/default.yaml && 
         python -m scripts.eval && 
         coverage run -m src.unit_tests.test_preprocess && 
         coverage report -m"
    ports:
      - 8000:8000
    image: borisshapa/wine-quality:latest