seed: 21
wandb: ~

data:
  train_data: data/train.csv
  val_data: data/val.csv
  cat_features_indices: [0]

model:
  iterations: 1000
  learning_rate: 0.1
  depth: 10
  l2_leaf_reg: 3
  task_type: "CPU"